from __future__ import annotations

from .schemas import ToolContract


def builtin_tool_contracts() -> list[ToolContract]:
    contracts = [
        ToolContract(
            tool_id="xref.get_startup_context",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"context": "startup_context"},
            requires_workspace=True,
            required_when="Client initialization must show base XRefKit control documents and link-resolution instructions before task routing.",
        ),
        ToolContract(
            tool_id="xref.list_knowledge_catalog",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"limit": "integer?"},
            output_schema={"entries": "knowledge_catalog_entries"},
            requires_workspace=True,
            required_when="Catalog browsing is needed without expanding knowledge body.",
        ),
        ToolContract(
            tool_id="xref.search_knowledge_catalog",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"query": "string", "limit": "integer?"},
            output_schema={"entries": "knowledge_catalog_entries"},
            requires_workspace=True,
            required_when="A purpose or question must be matched to XID-backed knowledge.",
        ),
        ToolContract(
            tool_id="xref.expand_knowledge",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"xid": "string"},
            output_schema={"entry": "knowledge_catalog_entry", "content": "markdown"},
            requires_workspace=True,
            required_when="The consumer explicitly needs the selected knowledge body.",
        ),
        ToolContract(
            tool_id="xref.get_document_by_xid",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"xid": "string"},
            output_schema={"document": "xref_document"},
            requires_workspace=True,
            required_when="Transferred content has a links[] entry whose xid must be resolved because the client does not have local Markdown files.",
        ),
        ToolContract(
            tool_id="xref.build_knowledge_context",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"query": "string", "limit": "integer?"},
            output_schema={"entries": "expanded_knowledge", "missing": "array"},
            requires_workspace=True,
            required_when="A bounded context pack is needed for a task.",
        ),
        ToolContract(
            tool_id="xref.list_skills",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"limit": "integer?"},
            output_schema={"entries": "skill_catalog_entries"},
            requires_workspace=True,
            required_when="Available Skills must be listed without executing them.",
        ),
        ToolContract(
            tool_id="xref.get_skill",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"skill_id": "string"},
            output_schema={"entry": "skill_catalog_entry"},
            requires_workspace=True,
            required_when="The client needs a Skill's meta/procedure content and skill_links that are resolved through get_document_by_xid.",
        ),
        ToolContract(
            tool_id="xref.list_workflows",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"entries": "workflow_catalog_entries"},
            requires_workspace=True,
            required_when="The client needs visible workflow order and flow definitions before routing work.",
        ),
        ToolContract(
            tool_id="xref.rank_skills_for_purpose",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"purpose": "string", "limit": "integer?"},
            output_schema={"results": "skill_rank_results"},
            requires_workspace=True,
            required_when="The consumer needs candidate Skills with evidence, not an automatic decision.",
        ),
        ToolContract(
            tool_id="xref.list_tool_contracts",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"contracts": "tool_contracts"},
            requires_workspace=False,
            required_when="The client performs capability handshake or audit.",
        ),
        ToolContract(
            tool_id="xref.get_client_tool_manifest",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"distribution": "client_tool_distribution"},
            requires_workspace=True,
            required_when="The client needs to know which Python tools can be installed for client-side execution.",
        ),
        ToolContract(
            tool_id="xref.get_client_tool_file",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"path": "string"},
            output_schema={"file": "client_tool_file"},
            requires_workspace=True,
            required_when="The client needs one distributed tool file content by manifest path.",
        ),
        ToolContract(
            tool_id="xref.get_client_tool_bundle",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"distribution": "client_tool_distribution", "files": "client_tool_files"},
            requires_workspace=True,
            required_when="The client needs to install all distributable Python tools for client-side execution.",
        ),
        ToolContract(
            tool_id="xref.get_client_tool_pip_package",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"package": "client_tool_pip_package"},
            requires_workspace=True,
            required_when="The client wants a pip-installable zip package for client-side XRefKit Python tools.",
        ),
        ToolContract(
            tool_id="xref.check_client_tool_versions",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"installed": "object"},
            output_schema={"result": "client_tool_version_check"},
            requires_workspace=True,
            required_when="Client initialization must compare installed client-side tool package versions with the server manifest.",
        ),
    ]
    for contract in contracts:
        contract.validate()
    return contracts
